name: docs-env
channels:
  - conda-forge
  - defaults
dependencies:
  # Scientific packages (Conda is much better at installing these)
  - python=3.12
  - numpy>=2.0
  - scipy>=1.10
  - h5py>=3.12
  - pandas>=2.0.3
  - matplotlib>=3.7.1
  # Documentation tools
  - pip
  - sphinx
  - sphinx-rtd-theme
  # Dependencies needed for local package installation
  - setuptools
  - wheel
  # Use pip to install the rest of your documentation requirements
  - pip:
    - -r docs/requirements.txt # Includes things like openpyxl, pyperclip, brimfile, etc.